site_name: Pantheon on Kalabox Documentation
theme: readthedocs
repo_url: https://github.com/kalabox/kalabox-app-pantheon
include_search: true
markdown_extensions:
  - markdown.extensions.toc
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
pages:
  - 'Homepage': 'index.md'
  - 'For Users':
    - 'Installation': 'users/install.md'
    - 'Using the CLI': 'users/cli.md'
    - 'Using the GUI': 'users/gui.md'
    - 'Services': 'users/services.md'
    - 'Dev Tools': 'users/tooling.md'
    - 'Configuration': 'users/config.md'
    - 'Best Practices': 'users/best.md'
  - 'For Developers':
    - 'Installation from Source': 'developers/install.md'
    - 'Contributing': 'developers/contrib.md'
    - 'Testing': 'developers/testing.md'
    - 'Building': 'developers/building.md'

