#!/bin/bash

# Use our custom php.ini
if [ -f "/src/config/php/php.ini" ]; then
  rm ${HOME}/.phpbrew/php/php-${PHP_VERSION}/etc/php.ini
  cp /src/config/php/php.ini ${HOME}/.phpbrew/php/php-${PHP_VERSION}/etc/php.ini
fi

# We need to do this for SSH add now as well
if [ -f "/ssh/.ssh/{$SSH_KEY}" ]; then
  eval `ssh-agent -s` > /dev/null
  ssh-add /ssh/.ssh/${$SSH_KEY} > /dev/null
fi

source /root/.phpbrew/bashrc > /dev/null
phpbrew -d switch ${PHP_VERSION} > /dev/null

$DRUSH_VERSION "$@"
