#!/bin/bash

# Terminus requires 5.5.24 now
PHP_VERSION=5.5.24

# Use our custom terminus php.ini We want to use a custom ini here so we can
# set error reporting so that notices are not reported to stderr
if [ -f "/src/config/terminus/php.ini" ]; then
  rm ${HOME}/.phpbrew/php/php-${PHP_VERSION}/etc/php.ini
  cp /src/config/terminus/php.ini ${HOME}/.phpbrew/php/php-${PHP_VERSION}/etc/php.ini
fi

# We need to do this for SSH add now as well
if [ -f "/ssh/.ssh/${SSH_KEY}" ]; then
  eval `ssh-agent -s` > /dev/null
  # By default ssh-add reports to stderr which in some circumstances can
  # cause kbox to error. We are going to pipe STDERR to /dev/null for now
  # for two main reasons
  #   1. If kbox actually gets to this point this is very unlikely to fail
  #   2. If it does fail its going to get reported downstream in an obvious way
  # I realize this is somewhat sacrilegious but im ok with that
  ssh-add /ssh/.ssh/${SSH_KEY} 2> /dev/null
fi

# Set the terminus cache file correctly
# @todo: eventually get this to load the correct session for the app
mkdir -p /src/config/terminus/cache
cp -f /ssh/.kalabox/terminus/session/${PANTHEON_ACCOUNT} /src/config/terminus/cache/session

source /root/.phpbrew/bashrc > /dev/null
phpbrew -d switch ${PHP_VERSION} > /dev/null

terminus "$@" #1> /src/config/terminus/stdout 2> /src/config/terminus/stderr
#echo $?
