#
# Kalabox Pantheon compose file
#
# This contains the core service definitions for Pantheon-on-Kalabox. This
# is a docker-compose file so please check out the compose file documentation
# over at https://docs.docker.com/compose/compose-file/.
#
# There are, however, a few caveats to take into account kalabox-compose.ymls
#
#   1. It is probably a bad idea to use the `container_name` key.
#
#   2. You can run `kbox env` inside of your app for a list of environmental
#      variables that you can use inside of this compose file.
#
#   3. Ports need to be exposed to the host on the outside using
#
#      ports:
#       - "PORTNUMBER"
#
#      Otherwise they are not usable in the services plugin.
#
#    4. The config directory in your app root contains a lot of
#       service config that is shared into each service. This is all
#       editable directly and should take on a `kbox restart`.
#

#
# This defines a data container to share common Pantheon app assets such as:
#
#   1. /media - Static assets like images and compiled css, Your files/wp-uploads
#               directory is symlinked here
#
#   2. /certs - Shared service certs
#
#   3. /sql - MariaDB databases to preserve data on rebuilds
#
#   4. /code - Your applications codebase, also where you shared code lives
#
#   5. /backups - Backups that are downloaded from Pantheon
#
data:
  image: busybox
  volumes:
    - $KALABOX_APP_ROOT_BIND/files:/media:rw
    - /certs
    - /sql
    - /code
    - /backups

#
# This defines a Pantheon appserver.
#
# We are currently running the same services as the Pantheon appserver with
# the current exception of apache tika.
#
# We also populate this service with similar environmental variables to what
# you would find on the pantheon appserver so you can make use of things
# like:
#
#   PRESSFLOW_SETTINGS
#   PANTHEON_ENVIRONMENT
#   CACHE_HOST
#
# Check your services config in kalabox.yml on how to access this directly
# instead of going through the edge service.
#
appserver:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/pantheon-appserver:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/pantheon-appserver

  hostname: $KALABOX_APP_HOSTNAME
  ports:
    - "8888"
    - "444"
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
  links:
    - db:database
    - redis:redis
    - solr:solr
  environment:
    TERM: xterm
    DOMAIN: $KALABOX_DOMAIN
    FRAMEWORK: $KALABOX_APP_PANTHEON_FRAMEWORK
    PHP_VERSION: $KALABOX_APP_PANTHEON_CONFIG_PHP
    DOCROOT: $KALABOX_APP_PANTHEON_DOCROOT
    FILEMOUNT: $KALABOX_APP_PANTHEON_FILEMOUNT
    DRUPAL_HASH_SALT: $KALABOX_APP_PANTHEON_DRUPAL_HASH_SALT
    DB_HOST: $KALABOX_APP_PANTHEON_DB_HOST
    DB_PORT: $KALABOX_APP_PANTHEON_DB_PORT
    DB_USER: $KALABOX_APP_PANTHEON_DB_USER
    MYSQL_HOST: $KALABOX_APP_PANTHEON_DB_HOST
    DB_PASSWORD: $KALABOX_APP_PANTHEON_DB_PASSWORD
    DB_NAME: $KALABOX_APP_PANTHEON_DB_NAME
    PANTHEON_ACCOUNT: $KALABOX_APP_PANTHEON_PANTHEON_ACCOUNT
    PANTHEON_SITE: $KALABOX_APP_PANTHEON_PANTHEON_SITE
    PANTHEON_SITE_NAME: $KALABOX_APP_PANTHEON_PANTHEON_SITE_NAME
    PANTHEON_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_ENVIRONMENT
    PANTHEON_INFRASTRUCTURE_ENVIRONMENT: $KALABOX_APP_PANTHEON_PANTHEON_INFRASTRUCTURE_ENVIRONMENT
    PRESSFLOW_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    BACKDROP_SETTINGS: $KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS
    CACHE_HOST: $KALABOX_APP_PANTHEON_CACHE_HOST
    CACHE_PORT: $KALABOX_APP_PANTHEON_CACHE_PORT
    CACHE_PASSWORD: $KALABOX_APP_PANTHEON_CACHE_PASSWORD
    PANTHEON_INDEX_HOST: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_HOST
    PANTHEON_INDEX_PORT: $KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT
    AUTH_KEY: $KALABOX_APP_PANTHEON_AUTH_KEY
    SECURE_AUTH_KEY: $KALABOX_APP_PANTHEON_SECURE_AUTH_KEY
    LOGGED_IN_KEY: $KALABOX_APP_PANTHEON_LOGGED_IN_KEY
    AUTH_SALT: $KALABOX_APP_PANTHEON_AUTH_SALT
    SECURE_AUTH_SALT: $KALABOX_APP_PANTHEON_SECURE_AUTH_SALT
    LOGGED_IN_SALT: $KALABOX_APP_PANTHEON_LOGGED_IN_SALT
    NONCE_SALT: $KALABOX_APP_PANTHEON_NONCE_SALT
#
# This defines a Pantheon database server.
#
db:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/pantheon-mariadb:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: ./dockerfiles/pantheon-mariadb

  ports:
    - "3306"
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data

#
# This defines a Pantheon edgeserver.
#
# This defines SSL termination and varnish configuration to mimic Pantheon.
# This is what serves your page when you go to appname.kbox. Check
# your services config on how to change or bypass this.
#
edge:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/pantheon-edge:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: dockerfiles/pantheon-edge

  links:
    - appserver:web
  volumes:
    - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
  environment:
    DOMAIN: $KALABOX_DOMAIN
  ports:
    - "80"
    - "443"

#
# This defines a Pantheon redis server.
#
# You should be able to use redis the same way you do on pantheon by
# following:
#   https://pantheon.io/docs/articles/sites/redis-as-a-caching-backend/
#
redis:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/pantheon-redis:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: dockerfiles/pantheon-redis

#
# This defines a Pantheon solr server.
#
# You should be able to use solr the same way you do on pantheon by
# following:
#   https://pantheon.io/docs/articles/sites/apache-solr/
#
solr:

  # Comment this and uncomment 'build' below if you want to edit your
  # local dockerfile and build from there. This is useful for development
  image: kalabox/pantheon-solr:$KALABOX_APP_PANTHEON_CONFIG_IMAGES

  # Uncomment this and comment 'image' above if you want to edit your
  # local dockerfile and build from there. This is useful for development
  #
  # build: dockerfiles/pantheon-solr

  volumes:
   - $KALABOX_APP_ROOT_BIND:/src:rw
  volumes_from:
    - data
