<?php

define('PANTHEON_INFRASTRUCTURE_ENVIRONMENT', getenv('PANTHEON_INFRASTRUCTURE_ENVIRONMENT'));
define('PANTHEON_SITE', getenv('PANTHEON_SITE'));
define('PANTHEON_ENVIRONMENT', getenv('PANTHEON_ENVIRONMENT'));
#define('PANTHEON_BINDING', getenv('PANTHEON_ENVIRONMENT'));

define('PANTHEON_DATABASE_HOST', getenv('DB_HOST'));
define('PANTHEON_DATABASE_PORT', getenv('DB_PORT'));
define('PANTHEON_DATABASE_USERNAME', getenv('DB_USER'));
define('PANTHEON_DATABASE_PASSWORD', getenv('DB_PASSWORD'));
define('PANTHEON_DATABASE_DATABASE', getenv('DB_NAME'));
#define('PANTHEON_DATABASE_BINDING', getenv('PANTHEON_ENVIRONMENT'));

define('PANTHEON_REDIS_HOST', getenv('CACHE_HOST'));
define('PANTHEON_REDIS_PORT', getenv('CACHE_PORT'));
define('PANTHEON_REDIS_PASSWORD', getenv('CACHE_PASSWORD'));
#define('PANTHEON_VALHALLA_HOST', 'valhalla2.cluster.panth.io');
