# Standard mariadb 5.5 container

FROM mariadb:5.5

#
# Add your custom stuff here, you will want to make sure
# you switch from `image` to `build` mode in the relevant
# .yml compose file.
#
# For more information on dockerfiles see:
#
#   https://docs.docker.com/engine/reference/builder/
#
